services:
  app:
    build: .
    container_name: docker-practice-container
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports: 
      - 80:80
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: docker-practice-redis-container
